version: "3.7"

services:
  garage:
    container_name: garage
    image: home.garage
    build: .
    hostname: garage
    restart: always
    networks:
      default:
        aliases:
          - garage

networks:
  default:
    name: iot_gateway
    external: true
